export const prepareXml = (content: CommonTypes.InputType) => {
  const {
    City,
    CountrySym,
    CustomerType,
    Email,
    FirstName,
    Flat,
    House,
    InputCity,
    InputDate,
    LastName,
    Name,
    PPE_City,
    PPE_CountrySym,
    PPE_Email,
    PPE_FirstName,
    PPE_Flat,
    PPE_House,
    PPE_LastName,
    PPE_Parcel,
    PPE_Phone,
    PPE_Street,
    PPE_Zipcode,
    Parcel,
    PersonalId,
    Phone,
    PodCode,
    PostOffice,
    ReceiverType,
    SellerCode,
    Street,
    TaxId,
    UsrEndDate,
    Zipcode,
  } = content;

  return `<?xml version="1.0" encoding="UTF-8"?>
        <ReserveSaleData>
            <InputDate>${InputDate}</InputDate>
            <ReceiverType>${ReceiverType}</ReceiverType>
            <InputCity>${InputCity}</InputCity>
            <SellerCode>${SellerCode}</SellerCode>
            <Urd1>
                <Name>${Name}</Name>
                <FirstName>${FirstName}</FirstName>		
                <LastName>${LastName}</LastName>
                <TaxId>${TaxId}</TaxId>
                <PersonalId>${PersonalId}</PersonalId>
                <Email>${Email}</Email>
                <Phone>${Phone}</Phone>
                <Address>
                    <Zipcode>${Zipcode}</Zipcode>
                    <City>${City}</City>
                    <Street>${Street}</Street>
                    <House>${House}</House>
                    <Flat>${Flat}</Flat>
                    <Parcel>${Parcel}</Parcel>
                    <CountrySym>${CountrySym}</CountrySym>
                </Address>
                <CustomerType>${CustomerType}</CustomerType>
            </Urd1>
            <PodReserveSale>
                <PodCode>${PodCode}</PodCode>
                <Address>
                    <Zipcode>${PPE_Zipcode}</Zipcode>
                    <City>${PPE_City}</City>
                    <Street>${PPE_Street}</Street>
                    <House>${PPE_House}</House>
                    <Flat>${PPE_Flat}</Flat>
                    <Parcel>${PPE_Parcel}</Parcel>
                    <CountrySym>${PPE_CountrySym}</CountrySym>
                    <PostOffice>${PostOffice}</PostOffice>
                </Address>
            </PodReserveSale>
            <UsrEndDate>${UsrEndDate}</UsrEndDate>
            <Submitter>
                <FirstName>${PPE_FirstName}</FirstName>	
                <LastName>${PPE_LastName}</LastName>	
                <Phone>${PPE_Phone}</Phone>
                <Email>${PPE_Email}</Email>
            </Submitter>
        </ReserveSaleData>
    `;
};
